### PR TITLE
Make Nx run to read from Nx cache

### PR DESCRIPTION
**Pull request by jukben**
https://github.com/jukben/fish-nx/pull/3#issuecomment-1958890757

### CODE REVIEW

**Comment by hassankhan** [comment]
https://github.com/jukben/fish-nx/pull/3#issuecomment-1959072727

**Comment by hassankhan** [comment]
In a project using `nx@17.2.8`, I don't seem to have a `.cache/nx/nxdeps.json` file; however I do have a `.nx/cache/project-graph.json` file though that seems like it has all projects and their targets in there.

**Comment by hassankhan** [comment]
Just to confirm, I created a new nx monorepo and the only file I see is at `.nx/cache/project-graph.json`

**Comment by jukben** [comment]
I don't want to over-engineer it It should kinda work for the latest one (you can eventually always force older version of this plugin). Let's aim for multiple ifs that should do for now.

btw my output

```
$ nx --version
15.1.1
```

**Comment by jukben** [comment]
I realized that in our configuration we override the cache folder, so I added logic to determine the cache folder first. Now it should be ready 🚀 Can you take a look?

**Comment by hassankhan** [comment]
> I don't want to over-engineer it It should kinda work for the latest one (you can eventually always force older version of this plugin). Let's aim for multiple ifs that should do for now.

I totally agree, but there another reason to use the version number - a fair amount of the commands aren't available on newer versions of `nx` (mostly the `affected:*` ones). In [my own version of the completions](https://github.com/hassankhan/dotfiles/blob/master/stow/fish/.config/fish/completions/nx.fish), I've completely replaced the old commands but I realize that might not work for you (or people with older nx versions).

> Can you take a look?

I just did and it seems to work brilliantly - even on my much smaller projects I can feel a significant speed boost 🎉

**Comment by jukben** [comment]
Can you prepare PR cleaning the old commands? I think it makes sense to stay as close with never version possible. I can always pin old version in `fisher`. 🙏

**Comment by hassankhan** [comment]
Sorry I forgot all about this, thanks for sorting it out 👍

**Pull request merged**
