### PR TITLE
Updates to add completions for newer nx projects

### PR DESCRIPTION
**Pull request by hassankhan**

### CODE REVIEW

**Comment by jukben** [comment]
Oh, wonderful! I haven't been using Nx for a while until this month where I started on a new project where it's already using the new (not that new though :D ) format. So I realized I need to update it – well not anymore! Thanks sir! 🙇

**Comment by jukben** [comment]
It looks there might be bug – or at least it does't work for my project. Let me try to wire some fix for it.

**Comment by hassankhan** [comment]
@jukben Have you got `fd` installed? If so, would you mind trying it instead of `find` and seeing if the performance improves for you?

**Comment by jukben** [comment]
That's just slightly better – like not 7s but 6.7s 😅. The problem is that (I guess) it runs sequentially (find -> read -> save to variable for later usage...). 

I was thinking about some hack to overcome it and dig into Nx's caches and look! It's order of magnitude faster because they already precompile it as part of nx runs.. obviously it will require to run nx before, but it handles cache invalidations, etc. so I think this is good compromise, thougths?

```
function __nx_run
    if test -e nx.json; and type -q jq
        if test -e .cache/nx/nxdeps.jsona
            jq -r '.nodes | to_entries | map("\(.key as $project | .value.data.targets | keys | map("\($project):\(.)") | .[])") | .[]' .cache/nx/nxdeps.json
        end
    else if test -e workspace.json; and type -q jq
        jq -r '.projects | to_entries | map("\(.key as $project | .value.targets | keys | map("\($project):\(.)") | .[])") | .[]' workspace.json
    end
end
```

**Comment by hassankhan** [comment]
I think that's pretty awesome, but might cause issues on fresh projects. I'm not sure which commands make `nx` populate the cache, and in my project I don't even seem to have a `.cache/nx/nxdeps.json` so I'm not 100% sure the approach will work for every nx monorepo.

That said, I think the ideal solution would look like:

- Check for `.cache/nx/nxdeps.json`
  - If found, use it for completions
  - If not found, 
    - Run the `nx` command that will populate the cache
    - Otherwise parse using `fd` + `jq` (as I did in the PR)

WDYT?

**Pull request merged**
